version: "3.8"
services:
    # Application
    greenbox-app:
        build:
            context: ./docker/services/app
            dockerfile: app.dockerfile
        working_dir: /var/www
        env_file: .env
        volumes:
            - ./:/var/www
        networks:
            - gf-network

    # Web Server
    greenbox-web:
        build:
            context: ./docker/services/web
            dockerfile: web.dockerfile
        working_dir: /var/www
        restart: always
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        networks:
            - gf-network

    # Database
    greenbox-database:
        image: mysql:8.0.25
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: greenbox_db
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_TCP_PORT: 3307
        ports:
            - "3307:3307"
        networks:
            - gf-network

networks:
    gf-network:
        name: "grocery-farming-network"